

ALTER FUNCTION [dbo].[SI_FN_ADD_DIAS_UTEIS](
  @DATA      DATE,
  @DIAS_UTEIS     INT   ,
  @CODCLIFOR INT

) RETURNS DATETIME   
/* CRIADO POR NILZA EM 13/08/2021 - CONSIDERAR OS DIAS UTEIS PARA O LEAD TIME DOS CONHECIMENTOS
ALTERADO POR NILZA EM 28/12/2021 - INCLUIDO TABELA DE FERIADOS - RODFER
*/
BEGIN  

 IF @DATA IS NULL
         BEGIN       
           SET @DATA = GETDATE();
         END

	   DECLARE @DIAS  INT  = 0
       DECLARE @CONTADOR      INT  = 0
       DECLARE @NOVA_DATA DATE = DATEADD(DAY, 1, @DATA) 
	   ----- LOCALIZA QUAL PADRÃO DE PRAZO DE ENTREGA DO CLIENTE (PELA NOTA, CTE OU OCS)
	   DECLARE @TIPDLE INT = ISNULL((SELECT TIPDLE FROM RODCLI WHERE CODCLIFOR = @CODCLIFOR),0)
	 
	
	
	IF @TIPDLE IN (0,1)

	   WHILE @CONTADOR < @DIAS_UTEIS 
        BEGIN 
          --IF @TIPDLE IN (0,1)
				  IF DATEPART(WEEKDAY, @NOVA_DATA) NOT IN (7,1) AND (SELECT TOP 1 RODFER.DATA FROM RODFER WHERE CONVERT(DATE,DATA) = CONVERT(DATE,@NOVA_DATA)) IS NULL
					SET @CONTADOR += 1;
					SELECT @NOVA_DATA = DATEADD(DAY, 1, @NOVA_DATA), @DIAS += 1;
		
		 END
	IF @TIPDLE IN (4)

	   WHILE @CONTADOR < @DIAS_UTEIS 
        BEGIN 
          --IF @TIPDLE IN (0,1)
				  IF DATEPART(WEEKDAY, @NOVA_DATA) NOT IN (1) AND (SELECT TOP 1 RODFER.DATA FROM RODFER WHERE CONVERT(DATE,DATA) = CONVERT(DATE,@NOVA_DATA)) IS NULL
					SET @CONTADOR += 1;
					SELECT @NOVA_DATA = DATEADD(DAY, 1, @NOVA_DATA), @DIAS += 1;
		 END
	IF @TIPDLE IN (2)

	   WHILE @CONTADOR < @DIAS_UTEIS 
        BEGIN 
          --IF @TIPDLE IN (0,1)
				  IF DATEPART(WEEKDAY, @NOVA_DATA)  IN (1,2,3,4,5,6,7)  --AND (SELECT TOP 1 RODFER.DATA FROM RODFER WHERE CONVERT(DATE,DATA) = CONVERT(DATE,@NOVA_DATA)) IS NULL
					SET @CONTADOR += 1;
					SELECT @NOVA_DATA = DATEADD(DAY, 1, @NOVA_DATA), @DIAS += 1;


		END 

		 RETURN DATEADD(DAY, @DIAS, @DATA);
  END
GO


